name: DePloY
on:
  push:
    branches: master

jobs:
  DePloY:
    runs-on: "ubuntu-latest"
    steps:
      - name: Deploying...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          script: |
            cd /var/maniabots-xyz
            git pull origin master
            pm2 restart 4
